local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-e>f', builtin.find_files, {})
vim.keymap.set('n', '<C-e>g', builtin.git_files,{})
vim.keymap.set('n', '<C-e>p', function()
	builtin.grep_string({search = vim.fn.input("Grep > ")})
end)
